name: kitchen-all-v0
args: []
kw_init_option_modelargs: {}
obs_dim: 60
action_dim: 9
action_min: null
action_max: null

# BeT baseline
# load_dir: "/home/liubove/Documents/my-packages/bet/exp_local/2024.10.15/105443_kitchen_train"
# BeT with zero option but skip connection
# load_dir: "/home/liubove/Documents/my-packages/bet/exp_local/2024.10.15/142452_kitchen_train"
# Hierarchical BeT
load_dir: "/home/liubove/Documents/my-packages/bet/exp_local/2024.10.28/154359_kitchen_train"

workspace:
  _target_: workspaces.adept_kitchen.AdeptKitchenWorkspace

dataset_fn:
  _target_: dataloaders.trajectory_loader.get_relay_kitchen_train_val
  data_directory: ${env_vars.datasets.relay_kitchen}
  window_size: ${window_size}
