name: kitchen-all-v0
args: []
kw_init_option_modelargs: {}
obs_dim: 60
action_dim: 9
action_min: null
action_max: null

# BeT baseline
# load_dir: "/home/liubove/Documents/my-packages/bet/exp_local/2024.10.15/105443_kitchen_train"
# BeT with zero option but skip connection
# load_dir: "/home/liubove/Documents/my-packages/bet/exp_local/2024.10.15/142452_kitchen_train"
# Hierarchical BeT
# load_dir: "/home/liubove/Documents/my-packages/bet/exp_local/2025.02.02/150340_kitchen_train"
# Supervised
# load_dir: "/home/liubove/Documents/my-packages/bet/exp_local/2025.02.15/183003_kitchen_train"
# Unsupervised
load_dir: "/home/liubove/Documents/my-packages/bet/exp_local/2025.02.15/183029_kitchen_train"
# Random 20% updates every epoch
# load_dir: "/home/liubove/Documents/my-packages/bet/exp_local/2025.02.17/105933_kitchen_train"
# Random 20% didn't update at any point.
# load_dir: "/home/liubove/Documents/my-packages/bet/exp_local/2025.02.15/182943_kitchen_train"
# Iterative random
# load_dir: "/home/liubove/Documents/my-packages/bet/exp_local/2025.02.17/113116_kitchen_train" 
workspace:
  _target_: workspaces.adept_kitchen.AdeptKitchenWorkspace

dataset_fn:
  _target_: dataloaders.trajectory_loader.get_relay_kitchen_train_val
  data_directory: ${env_vars.datasets.relay_kitchen}
  window_size: ${window_size}
